### ISSUE TITLE
Issues with direct Roblox Studio integration

### ISSUE THREAD

**Issue by ghost** [pitch-rbx/pitch#1]
From what I'm witnessing, the project in `main` appears to want to make a plugin directly inside Studio that streamlines the process of installing and running itch.io plugins

There's nothing wrong with this, I just wanted to chime in an issue with Roblox Studio *itself* that may not make this as easy as it first seems.

## The PluginLoader
When Roblox loads plugins, it internally creates a `fileName` binding that cant be set or read from any Lua code. There's a few values this can be, but in the sake of this, I imagine we'd be working with the `local_fileName` binding.

So for example, the loader loading a plugin by the name of `Browser.rbxm` would give it the internal binding of `local_Browser.rbxm`.

![image](https://user-images.githubusercontent.com/41757236/156334694-22f35834-d2fe-404f-94f0-a714b232ee45.png)

The actual bindings are to prevent collisions between plugins that could create various plugin objects with the same ID. If everything was running under a singleton plugin, everything would end up with the same binding, which reintroduces the problem of collisions.

## Things that dont work:
* Using `PluginManager():CreatePlugin() `- gets given a binding of `""` that cant be changed.
* Sandboxing the plugin object to create local_fileName.rbxm_loadedPlugin_id - works until we realise CreateToolbar cant be given a special ID as it sets the display name

Of course, if we're sandboxing the plugin object, it's possible to track whats loading what, and in the rare case we get a Toolbar ID collision, you could set it to PLUGIN_NAME: ToolbarID, but then how do we handle the issue of not actually knowing which toolbars are loading what

## Another Issue:
There's a long standing issue where Toolbars wont destroy themselves when we call PluginToolbar:Destroy(). This makes it impossible to actually unload plugins from another plugin, since Qt hasn't been told to actually remove the Toolbar when :Destroy() is called upon it's Lua object

## Closing Notes:
These issues are more of an issue if this attempts to provide backwards compatibility with plugins that are already running without needing to make significant changes to the base API that it uses.

I'm sure we could find a way around these issues, however I'm leaving these here as some hurdles that need to be overcome.

**Comment by jmkd3v** [comment]
We don't intend to support any hot reloading at the moment - our target is just getting a minimum viable product that can enable/disable things and the frontend, so I think we can close this for now
